### ISSUE TITLE
Writer Bot Missing Commands

### ISSUE THREAD

**Issue by Dhampir17** [writer-bot/bot#33]
Hello, 

Writer bot went offline for a bit yesterday and has been buggy since. One person started a sprint and the time period was set for 15 minutes, but more than 15 minutes passed and writer-bot didn't stop the sprint. When pinged about the current sprint, writer bot claimed there was no sprint in effect. 

No one else used it at that point and roughly 10 hours later, writer bot announced the end of the sprint and pinged the user for their word count update. 

Today, a sprint was started, but when the user tried to join it with a wordcount, the option to join with a wordcount was no longer listed. 

How do we fix this?

Thank you

**Comment by cwarwicker** [comment]
Hi, the bot has been up and down a lot as I've been fixing stuff. Is it still happening or is it ok now?

**Comment by Dhampir17** [comment]
Sorry to give you another thing to fix!

It will sprint properly, but the command /sprint join [initial] does not exist in the commands--this is across multiple servers.

**Comment by Dhampir17** [comment]
This is what it shows: [https://discord.com/channels/911405529157480499/911405529694371906/1065419800337190953](url)

In case the link didn't work, the options given are: 

sprint join same
sprint join no-wordcount
sprint join normal

The option to join with an initial wordcount is no longer listed.

**Comment by cwarwicker** [comment]
Those are the correct commands now. When you select `normal` you can also choose an optional initial word count, e.g. `/sprint join normal initial:100`

**Comment by Dhampir17** [comment]
Oh wow, thank you! I didn't know it was changed and when I tried normal before, I didn't see it gave you options. 

Thank you, I will pass on the word to other servers.
